###

GET http://localhost:4004/spm/payments

###

GET http://localhost:4004/sales-order/Payments

###Do not work

GET http://localhost:4004/spm/salesOrders(14355223812243766)

###

GET http://localhost:4004/spm/$metadata

###

GET http://localhost:4004/spm/sendPayment()